name: "Build project"
on:
  push:
    tags:
      - '*'
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --run "just build"
    - uses: softprops/action-gh-release@v2
      # Only release if tag begins with letter v
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: ./*.deb
